## Site Variables ##
title: Daniel Blake
author:
  name: Daniel Blake
  title: Front End Web Designer
  email: daniel@danielblake.design
  phone: 1-971-801-0208
  city: Portland, Oregon
  github: https://github.com/dmbdesignpdx
  linkedin: https://www.linkedin.com/in/danielblakepdx
  codepen: https://codepen.io/dmbdesignpdx

## Params ##
params:
# Theme
  theme: "#E6285D"

  # Open Graph / Twitter
  image: https://danielblake.design/img/daniel-og.png
  type: image/png


## Languages ##
defaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/en
    baseURL: https://danielblake.design
    copyright: |
      Copyright 2019 Daniel Blake. All rights reserved. All other trademarks are the property of their respective owners.


## Build ##
enableGitInfo: true
disableHugoGeneratorInject: true
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
  - robotsTXT
enableEmoji: true
