## Site Variables ##
baseURL: 'https://danielblake.design'
title: Daniel Blake - Front End Web Designer
author:
  name: Daniel Blake
  title: Front End Web Designer
  email: daniel@danielblake.design
  phone: 1-971-801-0208
  city: Portland
  state: Oregon
  github: 'https://github.com/dmbdesignpdx'
  linkedin: 'https://www.linkedin.com/in/danielblakepdx'
  codepen: 'https://codepen.io/dmbdesignpdx'

## Params ##
params:
# Theme
  theme: "#E13364"

  # Open Graph / Twitter
  image: 'https://danielblake.design/img/daniel-og.png'
  type: image/png


## Languages ##
defaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/en
    copyright: |
      Copyright 2019 Daniel Blake. All rights reserved. All other trademarks are the property of their respective owners.
  es:
    languageName: Español
    weight: 2
    contentDir: content/es
    copyright: |
      Copyright 2019 Daniel Blake. Todos los derechos reservados. Todas las demás marcas registradas son propiedad de sus respectivos dueños.

## Sitemap ##
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.9


## Build ##
enableGitInfo: true
disableHugoGeneratorInject: true
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
  - robotsTXT
enableEmoji: true
relativeURLs: true
