languageCode: en-us
baseURL: https://danielblake.design
title: Daniel Blake
author:
  name: Daniel Blake
copyright: 2018 Daniel Blake

enableGitInfo: true
disableKinds:
  - taxonomy
  - taxonomyTerm
  - RSS
disableHugoGeneratorInject: true
enableEmoji: true
