[build]
  publish = "public/"
  command = "env HUGO_ENV=production hugo --minify"

[context.production]
  HUGO_VERSION = "0.52"
  NODE_VERSION = "10.15.3"

[context.nightly]
  HUGO_VERSION = "0.54.0"
  NODE_VERSION = "11.13.0"
